"""empty message

Revision ID: 2c119961bad6
Revises: 4fabf3a0b9f6
Create Date: 2015-03-14 18:28:00.292468

"""

# revision identifiers, used by Alembic.
revision = '2c119961bad6'
down_revision = '4fabf3a0b9f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestion')
    ### end Alembic commands ###
