"""empty message

Revision ID: 34b4f3870193
Revises: 2c119961bad6
Create Date: 2015-03-14 20:41:31.670282

"""

# revision identifiers, used by Alembic.
revision = '34b4f3870193'
down_revision = '2c119961bad6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
