"""empty message

Revision ID: 4fabf3a0b9f6
Revises: 3ee88acf6d10
Create Date: 2015-03-14 14:44:43.505725

"""

# revision identifiers, used by Alembic.
revision = '4fabf3a0b9f6'
down_revision = '3ee88acf6d10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('iframe', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'iframe')
    ### end Alembic commands ###
